version: "3.9"
services:
  smartparkingconfig-db:
    container_name: smartparkingconfig-db
    image: postgres:latest
    environment:
      POSTGRES_DB: smartparkingconfig
      POSTGRES_USER: smartparkingconfig
      POSTGRES_PASSWORD: ${DB_PW_SmartParkingConfig}
      PGDATA: /var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U smartparkingconfig'] # <<<---
      interval: 5s
      timeout: 60s
      retries: 30
    volumes:
      - smartparkingconfig-db:/var/lib/postgresql/data
    expose:
      # Opens port 3306 on the container
      - '3306'
    networks:
      - backend
    restart: unless-stopped
      
  smartparkingconfig:
    image: smartparkingconfig:latest
    depends_on:
      smartparkingconfig-db:
        condition: service_healthy
    restart: on-failure
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://smartparkingconfig:5432/smartparkingconfig?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: smartparkingconfig
      SPRING_DATASOURCE_PASSWORD: ${DB_PW_SmartParkingConfig}
      KEYCLOAK_AUTH-SERVER-URL: https://${DOMAIN}/auth
      SERVER_USE_FORWARD_HEADERS: "true"
      SERVER_FORWARD_HEADERS_STRATEGY: FRAMEWORK
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - backend

volumes:
  smartparkingconfig-db:

 # Networks to be created to facilitate communication between containers
networks:
  backend:

