apiVersion: v2
name: observatory-config-chart
description: Smart Parking Config App

type: application

version: ${project.version}

appVersion: "${project.version}"

dependencies:
  - name: postgresql
    version: "12.11.2"
    repository: "oci://registry-1.docker.io/bitnamicharts"
