app:
  contextPath: "/"
  observatoryUrl: "http://internal-hostname/observatory"


auth:
  enabled: true
  keycloakRealmUrlInternal: http://internal-hostname/realms/smartparkingconfig
  keycloakRealmUrlExternal: https://external-hostname/realms/smartparkingconfig # will be used for readyness probe
  clientId: smartparkingconfig
  clientSecret: smartparkingconfig # TODO get from secret

postgresql:
  auth:
    database: smartparkingconfig
    username: smartparkingconfig
    password: smartparkingconfig

ingress:
  enabled: true
  hosts:
    - host: <<hostname>>
      paths:
        - path: /smartparkingconfig
          pathType: ImplementationSpecific