version: "3.9"
name: smartparkingconfig

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: smartparkingconfig
      POSTGRES_USER: smartparkingconfig
      POSTGRES_PASSWORD: smartparkingconfig
      PGDATA: /var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U smartparkingconfig']
      interval: 5s
      timeout: 60s
      retries: 30
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "5433:5432"
  
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin:/var/lib/pgadmin
       - ./pgadmin/postgreslocal-servers-config.json:/pgadmin4/servers.json
    ports:
      - "5050:80"

volumes:
  db:
  pgadmin: