name: observatory-config

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: observatory-config
      POSTGRES_USER: observatory-config
      POSTGRES_PASSWORD: observatory-config
      PGDATA: /var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U observatory-config']
      interval: 5s
      timeout: 60s
      retries: 30
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "5433:5432"
  
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin:/var/lib/pgadmin
       - ./pgadmin/postgreslocal-servers-config.json:/pgadmin4/servers.json
    ports:
      - "5050:80"

volumes:
  db:
  pgadmin: