version: "3.9"
services:
  postgres:
    container_name: smartparkingconfig-db
    image: postgres:latest
    environment:
      POSTGRES_DB: smartparkingconfig
      POSTGRES_USER: smartparkingconfig
      POSTGRES_PASSWORD: smartparkingconfig
      PGDATA: /var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U smartparkingconfig']
      interval: 5s
      timeout: 60s
      retries: 30
    volumes:
      - smartparkingconfig-db:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - backend
    restart: unless-stopped
  
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - smartparkingconfig-pgadmin:/var/lib/pgadmin
       - ./pgadmin/postgreslocal-servers-config.json:/pgadmin4/servers.json
    ports:
      - "5050:80"
    networks:
      - backend
    restart: unless-stopped

networks:
  backend:

volumes:
  smartparkingconfig-db:
  smartparkingconfig-pgadmin: