apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "smartparkingconfig.fullname" . }}
  labels:
    {{- include "smartparkingconfig.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "smartparkingconfig.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "smartparkingconfig.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
      - name: check-db-ready
        image: postgres:15.4
        command: ['sh', '-c', 
          'until pg_isready -h {{ include "postgresql.servicename" . }} -p 5432; 
          do echo waiting for database; sleep 2; done;']
      - name: wait-for-keycloak
        image: curlimages/curl:latest
        command: ["/bin/sh","-c"]
        args: ["while [ $(curl -sw '%{http_code}' {{ .Values.auth.keycloak_url }} -o /dev/null) -ne 200 ]; do sleep 5; echo 'Waiting for keycloak at {{ .Values.auth.keycloak_url }}'; done"]
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://{{ include "postgresql.servicename" . }}:5432/{{ .Values.postgresql.auth.database }}
            - name: SPRING_DATASOURCE_USERNAME
              value: {{ .Values.postgresql.auth.username }}
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "postgresql.secretname" . }}
                  key: password
            - name: SERVER_SERVLET_CONTEXT_PATH
              value: {{ .Values.app.context_path | quote }}
            - name: DATABACKEND_URL
              value: http://databackend-databackend-chart.{{ .Values.namespace }}.svc.cluster.local/databackend
            {{- if .Values.auth.enabled }}
            - name: SPRING_PROFILES_ACTIVE
              value: auth
            - name: SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_AUTHORIZATION-URI
              value: {{ .Values.auth.keycloakRealmUrlExternal }}/protocol/openid-connect/auth
            - name: SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_TOKEN-URI
              value: {{ .Values.auth.keycloakRealmUrlInternal }}/protocol/openid-connect/token
            - name: SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_USER-INFO-URI
              value: {{ .Values.auth.keycloakRealmUrlInternal }}/protocol/openid-connect/userinfo
            - name: SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_JWK-SET-URI
              value: {{ .Values.auth.keycloakRealmUrlInternal }}/protocol/openid-connect/certs
            - name: SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_USERNAMEATTRIBUTE
              value: preferred_username
            - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_AUTHORIZATION-GRANT-TYPE
              value: authorization_code
            - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_SCOPE
              value: openid
            - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_REDIRECT-URI
              value: "{baseUrl}/login/oauth2/code/{registrationId}"
            - name: KEYCLOAK-LOGOUT-URI
              value: {{ .Values.auth.keycloakRealmUrlExternal }}/protocol/openid-connect/logout
            - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_CLIENT-ID
              value: {{ .Values.auth.clientId }}
            - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_CLIENT-SECRET
              value: {{ .Values.auth.clientSecret }}
            {{- else }}
            - name: SPRING_PROFILES_ACTIVE
              value: default
            {{- end }}
            {{- with .Values.extraEnv }}
            {{- tpl . $ | nindent 12 }}
            {{- end }}
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ .Values.app.context_path }}/monitoring/health
              port: http
            initialDelaySeconds: 180
          readinessProbe:
            httpGet:
              path: {{ .Values.app.context_path }}/monitoring/health
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
