name: Build and Publish

on:
  pull_request:
    branches: [ master, versionupgrade ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    name: "Building project with Java 17"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: 17
    - name: setup node
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - run: npm --version
    - run: node --version
    - name: npm install
      run: |
        if [ -d "webclient/app" ]; then
          cd webclient/app
          npm install --legacy-peer-deps
        fi
    - name: Build with Maven
      run: mvn clean -B package -P frontend --file pom.xml
      env:
         CI: false
    - name: Upload Maven build artifact
      uses: actions/upload-artifact@v1
      with:
        name: artifact
        path: application/target/application-0.0.1-SNAPSHOT.jar
