name: Build & Push Helm Chart

on:
  workflow_dispatch:
    inputs:
      release-type: # id of input
        description: "prerelease, patch, minor or major"
        required: true
        default: "prerelease"

env:
    HELM_EXPERIMENTAL_OCI: 1

jobs:
  helm_push:
    runs-on: [self-hosted, linux, X64]
    steps:
    - uses: actions/checkout@master
    - uses: goodsmileduck/helm-push-action@v3
      env:
        SOURCE_DIR: './deployment/helm'
        CHART_FOLDER: 'smartparkingconfig'
        FORCE: 'True'
        CHARTMUSEUM_URL: ${{ vars.CHARTMUSEUM_URL }}
        CHARTMUSEUM_USER: ${{ secrets.CHARTMUSEUM_USER }}
        CHARTMUSEUM_PASSWORD: ${{ secrets.CHARTMUSEUM_PASSWORD }}