name: Build & Push Helm Chart

on:
    push:
        branches:
          - "feature/AB#912-Run-workflow-on-local-runner"

jobs:
  helm_push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: goodsmileduck/helm-push-action@v2
      env:
        SOURCE_DIR: './deployment/helm'
        CHART_FOLDER: 'smartparkingconfig'
        FORCE: 'True'
        CHARTMUSEUM_URL: ${{ vars.CHARTMUSEUM_URL }}
        CHARTMUSEUM_USER: ${{ secrets.CHARTMUSEUM_USER }}
        CHARTMUSEUM_PASSWORD: ${{ secrets.CHARTMUSEUM_PASSWORD }}